import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/List.module.css'
import MapListEntity from '@/components/MapListEntity'
import { useMapData } from '@/lib/useMapData'

const inter = Inter({ subsets: ['latin'] })

function Home() {
  const { data, isLoading, isError } = useMapData()

  if (isLoading) return <div>Loading...</div>

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <MapListEntity nodes={data.nodes} />
      </main>
    </>
  )
}

export default Home
